```js
// 情景：发送请求一后，发送请求二，如果上一个请求没有完成，直接取消请求

        let request = axios.create({

            baseURL: "http://localhost:3000"

        })

        // 用于保存取消请求的那个函数

        // 我们分析一下这段代码，为什么只有技术的请求会被取消

        let cancel = null
        axios.defaults.baseURL = "http://localhost:4000"
        function getProducts1() {
            if (typeof cancel === "function") {
                cancel()
            }
            axios.get("/products1", {
                cancelToken: new axios.CancelToken((c) => {
                    cancel = c;
                })
            }).then(response => {
                cancel = null
               console.log("已经成功请求产品1");
            }).catch(error => {
                cancel = null
                console.log(error.message, error)
            })
        }
        async function getProducts2() {
            if (typeof cancel === "function") {
                cancel()
            }
            axios.get("/products1", {
                cancelToken: new axios.CancelToken((c) => {
                    cancel = c;
                })
            }).then(response => {
                cancel = null
                console.log("已经成功请求产品1");
            }).catch(error => {
                cancel = null
                console.log(error.message, error)
            })
        }
        async function cancelReq() {
            if (typeof cancel === 'function') {
                cancel("强制取消请求")//里面可以传一个message
                // 执行取消请求后会主动进入请求失败的流程执行error，但是是一个reject的promise
            } else {
                console.log("没有可以取消的请求")
            }
        }
```![[QQ截图20230220110132.png]]
[javascript - axios取消功能详解 - 个人文章 - SegmentFault 思否](https://segmentfault.com/a/1190000039127387)![[尚硅谷_axios从入门到源码分析.pdf]]